
package com.pay.framework.payment.unionpay.moto.pay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.5-incubator
 * Tue Jan 20 16:50:31 CST 2015
 * Generated source version: 2.0.5-incubator
 * 
 */

@WebService(targetNamespace = "http://service.preMOTO.bjpos.com/", name = "PayDelegate")

public interface PayDelegate {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "pay", targetNamespace = "http://service.preMOTO.bjpos.com/", className = "com.pay.framework.payment.unionpay.moto.pay.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://service.preMOTO.bjpos.com/", className = "com.pay.framework.payment.unionpay.moto.pay.PayResponse")
    @WebMethod
    public java.lang.String pay(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
