
package com.pay.framework.payment.unionpay.moto.pay;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.pay.framework.payment.unionpay.moto.pay.PayDelegate;

/**
 * This class was generated by Apache CXF (incubator) 2.0.5-incubator
 * Tue Jan 20 16:50:31 CST 2015
 * Generated source version: 2.0.5-incubator
 * 
 */

@WebServiceClient(name = "PayService", targetNamespace = "http://service.preMOTO.bjpos.com/", wsdlLocation = "file:/E:/cxf/input/PayService.wsdl")
public class PayService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://service.preMOTO.bjpos.com/", "PayService");
    public final static QName PayPort = new QName("http://service.preMOTO.bjpos.com/", "PayPort");
    static {
        URL url = null;
        try {
            url = new URL("http://114.255.222.233:5004/preMOTO/PayPort?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://114.255.222.233:5004/preMOTO/PayPort?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PayPort
     */
    @WebEndpoint(name = "PayPort")
    public PayDelegate getPayPort() {
        return super.getPort(PayPort, PayDelegate.class);
    }

}
